import { createContext, useState, useEffect } from "react";

export const ResortData = createContext();

export default function ResortDataProvider({children}){
    const hotelData = [
                /* 한국 - 서울 */
            {
                id: 1,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-03-05",
                endDate: "2026-03-09",
                hotelName: "서울 스카이베이 프라임 호텔",
                price: 164000,
                img: ["/img/1-1.jpg","/img/1-2.jpg","/img/1-3.jpg","/img/1-4.jpg","/img/1-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["피트니스","레스토랑","편의점","라운지","엘리베이터","비즈니스센터"],
                roomservice: ["무선인터넷","욕실용품","에어컨","드라이기","샤워실","TV","전기주전자"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 4.5,
            scoreCount: 12320
            },

            {
                id: 2,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-03-18",
                endDate: "2026-03-22",
                hotelName: "서울 라이트하버 호텔",
                price: 142000,
                img: ["/img/2-1.jpg","/img/2-2.jpg","/img/2-3.jpg","/img/2-4.jpg","/img/2-5.jpg"],
                type: "Condo",
                quality: 3,
                publicService: ["레스토랑","사우나","편의점","라운지","엘리베이터","바베큐"],
                roomservice: ["무선인터넷","욕실용품","에어컨","냉장고","샤워실","TV"],
                otherService: ["카드결제","스프링클러","짐보관가능"],
                score: 3.5,
                scoreCount: 6811
            },

            {
                id: 3,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-04-10",
                endDate: "2026-04-14",
                hotelName: "서울 헤리티지 스타 라운지",
                price: 178000,
                img: ["/img/3-1.jpg","/img/3-2.jpg","/img/3-3.jpg","/img/3-4.jpg","/img/3-5.jpg"],
                type: "Hotel",
                quality: 5,
                publicService: ["피트니스","레스토랑","사우나","라운지","바","엘리베이터"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","전기주전자","TV","냉장고"],
                otherService: ["조식제공","무료주차","카드결제"],
                score: 4.5,
                scoreCount: 14952
            },

            {
                id: 4,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-04-22",
                endDate: "2026-04-26",
                hotelName: "서울 프레미어 모던 스테이",
                price: 98000,
                img: ["/img/4-1.jpg","/img/4-2.jpg","/img/4-3.jpg","/img/4-4.jpg","/img/4-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["편의점","라운지","레스토랑","엘리베이터","건조기","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","냉장고"],
                otherService: ["카드결제","짐보관가능","스프링클러"],
                score: 3.0,
                scoreCount: 4020
            },

            {
                id: 5,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-05-03",
                endDate: "2026-05-07",
                hotelName: "서울 오션루프 스위트",
                price: 156000,
                img: ["/img/5-1.jpg","/img/5-2.jpg","/img/5-3.jpg","/img/5-4.jpg","/img/5-5.jpg"],
                type: "Resort",
                quality: 4,
                publicService: ["야외수영장","라운지","피트니스","레스토랑","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","전기주전자","TV","냉장고"],
                otherService: ["무료주차","카드결제","조식제공"],
                score: 4.0,
                scoreCount: 8733
            },

            {
                id: 6,
                country: "Korea",
                city: "Seoul",
                startDate: "2026-05-28",
                endDate: "2026-06-01",
                hotelName: "서울 리버사이드 프라임 호텔",
                price: 133000,
                img: ["/img/6-1.jpg","/img/6-2.jpg","/img/6-3.jpg","/img/6-4.jpg","/img/6-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","편의점","라운지","엘리베이터","사우나","비즈니스센터"],
                roomservice: ["무선인터넷","욕실용품","에어컨","드라이기","샤워실","냉장고","TV"],
                otherService: ["카드결제","스프링클러","무료주차"],
                score: 3.5,
                scoreCount: 6911
            },

            /* 한국 - 부산 */

            {
                id: 7,
                country: "Korea",
                city: "Busan",
                startDate: "2026-03-06",
                endDate: "2026-03-10",
                hotelName: "부산 오션클라우드 호텔",
                price: 149000,
                img: ["/img/7-1.jpg","/img/7-2.jpg","/img/7-3.jpg","/img/7-4.jpg","/img/7-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["피트니스","레스토랑","라운지","바","엘리베이터","편의점"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV","전기주전자"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 4.0,
                scoreCount: 8221
            },

            {
                id: 8,
                country: "Korea",
                city: "Busan",
                startDate: "2026-03-22",
                endDate: "2026-03-26",
                hotelName: "부산 마리나 스위트",
                price: 172000,
                img: ["/img/8-1.jpg","/img/8-2.jpg","/img/8-3.jpg","/img/8-4.jpg","/img/8-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","바","사우나"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","드라이기","TV"],
                otherService: ["카드결제","짐보관가능","조식제공"],
                score: 4.5,
                scoreCount: 14300
            },

            {
                id: 9,
                country: "Korea",
                city: "Busan",
                startDate: "2026-04-04",
                endDate: "2026-04-08",
                hotelName: "부산 블루웨이브 호텔",
                price: 96000,
                img: ["/img/9-1.jpg","/img/9-2.jpg","/img/9-3.jpg","/img/9-4.jpg","/img/9-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["편의점","라운지","레스토랑","엘리베이터","바","건조기"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV"],
                otherService: ["스프링클러","카드결제","짐보관가능"],
                score: 3.0,
                scoreCount: 3890
            },

            {
                id: 10,
                country: "Korea",
                city: "Busan",
                startDate: "2026-04-18",
                endDate: "2026-04-22",
                hotelName: "부산 센트럴힐 호텔",
                price: 118000,
                img: ["/img/10-1.jpg","/img/10-2.jpg","/img/10-3.jpg","/img/10-4.jpg","/img/10-5.jpg"],
                type: "Condo",
                quality: 3,
                publicService: ["피트니스","레스토랑","사우나","편의점","엘리베이터","바베큐"],
                roomservice: ["무선인터넷","욕실용품","에어컨","드라이기","샤워실","TV","전기주전자"],
                otherService: ["무료주차","카드결제","스프링클러"],
                score: 3.5,
                scoreCount: 6143
            },

            {
                id: 11,
                country: "Korea",
                city: "Busan",
                startDate: "2026-05-02",
                endDate: "2026-05-06",
                hotelName: "부산 더레인 하버 스테이",
                price: 154000,
                img: ["/img/11-1.jpg","/img/11-2.jpg","/img/11-3.jpg","/img/11-4.jpg","/img/11-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","실내수영장","피트니스","라운지","바","엘리베이터"],
                roomservice: ["무선인터넷","욕실용품","에어컨","전기주전자","샤워실","냉장고","TV"],
                otherService: ["조식제공","무료주차","카드결제"],
                score: 4.0,
                scoreCount: 9122
            },

            {
                id: 12,
                country: "Korea",
                city: "Busan",
                startDate: "2026-05-27",
                endDate: "2026-05-31",
                hotelName: "부산 글로우 포레스트 호텔",
                price: 103000,
                img: ["/img/12-1.jpg","/img/12-2.jpg","/img/12-3.jpg","/img/12-4.jpg","/img/12-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 3770
            },

            /* 한국 - 강릉 */

            {
                id: 13,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-03-03",
                endDate: "2026-03-07",
                hotelName: "강릉 코랄베이 오션 호텔",
                price: 132000,
                img: ["/img/13-1.jpg","/img/13-2.jpg","/img/13-3.jpg","/img/13-4.jpg","/img/13-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","라운지","피트니스","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","냉장고","전기주전자"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 9101
            },

            {
                id: 14,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-03-19",
                endDate: "2026-03-23",
                hotelName: "강릉 마운틴힐 프라임 스테이",
                price: 89000,
                img: ["/img/14-1.jpg","/img/14-2.jpg","/img/14-3.jpg","/img/14-4.jpg","/img/14-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["라운지","편의점","건조기","레스토랑","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","냉장고"],
                otherService: ["짐보관가능","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 4210
            },

            {
                id: 15,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-04-02",
                endDate: "2026-04-06",
                hotelName: "강릉 블루하버 씨앤스테이",
                price: 156000,
                img: ["/img/15-1.jpg","/img/15-2.jpg","/img/15-3.jpg","/img/15-4.jpg","/img/15-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","피트니스","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","TV","냉장고"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.5,
                scoreCount: 13532
            },

            {
                id: 16,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-04-21",
                endDate: "2026-04-25",
                hotelName: "강릉 에코브리즈 호텔",
                price: 112000,
                img: ["/img/16-1.jpg","/img/16-2.jpg","/img/16-3.jpg","/img/16-4.jpg","/img/16-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","사우나","엘리베이터","라운지","편의점","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","드라이기","샤워실","TV","전기주전자"],
                otherService: ["카드결제","스프링클러","무료주차"],
                score: 3.5,
                scoreCount: 6120
            },

            {
                id: 17,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-05-05",
                endDate: "2026-05-09",
                hotelName: "강릉 소울베이 더스위트",
                price: 175000,
                img: ["/img/17-1.jpg","/img/17-2.jpg","/img/17-3.jpg","/img/17-4.jpg","/img/17-5.jpg"],
                type: "Condo",
                quality: 5,
                publicService: ["피트니스","레스토랑","라운지","엘리베이터","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","전기주전자","TV","냉장고","샤워실"],
                otherService: ["카드결제","짐보관가능","조식제공"],
                score: 4.5,
                scoreCount: 14321
            },

            {
                id: 18,
                country: "Korea",
                city: "Gangneung",
                startDate: "2026-05-28",
                endDate: "2026-06-01",
                hotelName: "강릉 씨사이드 리프 호텔",
                price: 98000,
                img: ["/img/18-1.jpg","/img/18-2.jpg","/img/18-3.jpg","/img/18-4.jpg","/img/18-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","레스토랑","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 4022
            },

            /* 한국 - 속초 */
            {
                id: 19,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-03-04",
                endDate: "2026-03-08",
                hotelName: "속초 오션브리즈 시티호텔",
                price: 128000,
                img: ["/img/19-1.jpg","/img/19-2.jpg","/img/19-3.jpg","/img/19-4.jpg","/img/19-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","라운지","피트니스","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","전기주전자","TV","냉장고"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 8243
            },

            {
                id: 20,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-03-21",
                endDate: "2026-03-25",
                hotelName: "속초 힐크레스트 베이뷰 리조트",
                price: 168000,
                img: ["/img/20-1.jpg","/img/20-2.jpg","/img/20-3.jpg","/img/20-4.jpg","/img/20-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","드라이기","TV"],
                otherService: ["무료주차","카드결제","조식제공"],
                score: 4.5,
                scoreCount: 13920
            },

            {
                id: 21,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-04-06",
                endDate: "2026-04-10",
                hotelName: "속초 블루문 스테이",
                price: 88000,
                img: ["/img/21-1.jpg","/img/21-2.jpg","/img/21-3.jpg","/img/21-4.jpg","/img/21-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["라운지","편의점","레스토랑","엘리베이터","바","건조기"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV"],
                otherService: ["카드결제","짐보관가능","스프링클러"],
                score: 3.0,
                scoreCount: 3920
            },

            {
                id: 22,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-04-23",
                endDate: "2026-04-27",
                hotelName: "속초 씨포레스트 마운틴뷰 호텔",
                price: 113000,
                img: ["/img/22-1.jpg","/img/22-2.jpg","/img/22-3.jpg","/img/22-4.jpg","/img/22-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","사우나","라운지","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","전기주전자","드라이기"],
                otherService: ["무료주차","카드결제","스프링클러"],
                score: 3.5,
                scoreCount: 6022
            },

            {
                id: 23,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-05-08",
                endDate: "2026-05-12",
                hotelName: "속초 클라우드베이 스위트",
                price: 151000,
                img: ["/img/23-1.jpg","/img/23-2.jpg","/img/23-3.jpg","/img/23-4.jpg","/img/23-5.jpg"],
                type: "Condo",
                quality: 5,
                publicService: ["피트니스","레스토랑","라운지","엘리베이터","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV","전기주전자"],
                otherService: ["카드결제","짐보관가능","조식제공"],
                score: 4.5,
                scoreCount: 14821
            },

            {
                id: 24,
                country: "Korea",
                city: "Sokcho",
                startDate: "2026-05-26",
                endDate: "2026-05-30",
                hotelName: "속초 레이크브리즈 캠프로그",
                price: 98000,
                img: ["/img/24-1.jpg","/img/24-2.jpg","/img/24-3.jpg","/img/24-4.jpg","/img/24-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","레스토랑","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 3801
            },

            /* 한국 - 경주 */

            {
                id: 25,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-03-02",
                endDate: "2026-03-06",
                hotelName: "경주 로열가든 힐스 호텔",
                price: 141000,
                img: ["/img/25-1.jpg","/img/25-2.jpg","/img/25-3.jpg","/img/25-4.jpg","/img/25-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","라운지","피트니스","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","전기주전자","TV","냉장고"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 9011
            },

            {
                id: 26,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-03-15",
                endDate: "2026-03-19",
                hotelName: "경주 크라운레이크 리조트",
                price: 163000,
                img: ["/img/26-1.jpg","/img/26-2.jpg","/img/26-3.jpg","/img/26-4.jpg","/img/26-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","드라이기","TV"],
                otherService: ["무료주차","조식제공","카드결제"],
                score: 4.5,
                scoreCount: 14012
            },

            {
                id: 27,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-04-01",
                endDate: "2026-04-05",
                hotelName: "경주 하모니 스테이션 게스트하우스",
                price: 82000,
                img: ["/img/27-1.jpg","/img/27-2.jpg","/img/27-3.jpg","/img/27-4.jpg","/img/27-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["라운지","편의점","레스토랑","건조기","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV"],
                otherService: ["카드결제","짐보관가능","스프링클러"],
                score: 3.0,
                scoreCount: 3711
            },

            {
                id: 28,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-04-18",
                endDate: "2026-04-22",
                hotelName: "경주 네이처힐 프리미어 호텔",
                price: 119000,
                img: ["/img/28-1.jpg","/img/28-2.jpg","/img/28-3.jpg","/img/28-4.jpg","/img/28-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","사우나","라운지","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","드라이기","TV","전기주전자"],
                otherService: ["무료주차","카드결제","스프링클러"],
                score: 3.5,
                scoreCount: 5903
            },

            {
                id: 29,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-05-07",
                endDate: "2026-05-11",
                hotelName: "경주 스카이라인 파노라마 콘도",
                price: 152000,
                img: ["/img/29-1.jpg","/img/29-2.jpg","/img/29-3.jpg","/img/29-4.jpg","/img/29-5.jpg"],
                type: "Condo",
                quality: 4,
                publicService: ["피트니스","레스토랑","라운지","엘리베이터","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","냉장고","전기주전자"],
                otherService: ["카드결제","조식제공","짐보관가능"],
                score: 4.0,
                scoreCount: 11021
            },

            {
                id: 30,
                country: "Korea",
                city: "Gyeongju",
                startDate: "2026-05-25",
                endDate: "2026-05-29",
                hotelName: "경주 포레스트캠프 휴글로우",
                price: 97000,
                img: ["/img/30-1.jpg","/img/30-2.jpg","/img/30-3.jpg","/img/30-4.jpg","/img/30-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","레스토랑","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 4102
            },

            /* 한국 - 여수 */

            {
                id: 31,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-03-03",
                endDate: "2026-03-07",
                hotelName: "여수 오션프레임 스테이",
                price: 146000,
                img: ["/img/31-1.jpg","/img/31-2.jpg","/img/31-3.jpg","/img/31-4.jpg","/img/31-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","편의점","라운지","피트니스","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","전기주전자","냉장고"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 9321
            },

            {
                id: 32,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-03-17",
                endDate: "2026-03-21",
                hotelName: "여수 블루코스트 리조트",
                price: 170000,
                img: ["/img/32-1.jpg","/img/32-2.jpg","/img/32-3.jpg","/img/32-4.jpg","/img/32-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","드라이기","TV"],
                otherService: ["무료주차","카드결제","조식제공"],
                score: 4.5,
                scoreCount: 14410
            },

            {
                id: 33,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-04-04",
                endDate: "2026-04-08",
                hotelName: "여수 베이하버 게스트하우스",
                price: 78000,
                img: ["/img/33-1.jpg","/img/33-2.jpg","/img/33-3.jpg","/img/33-4.jpg","/img/33-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["라운지","편의점","레스토랑","건조기","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV"],
                otherService: ["카드결제","짐보관가능","스프링클러"],
                score: 3.0,
                scoreCount: 3611
            },

            {
                id: 34,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-04-19",
                endDate: "2026-04-23",
                hotelName: "여수 클리프사운드 프라임 호텔",
                price: 124000,
                img: ["/img/34-1.jpg","/img/34-2.jpg","/img/34-3.jpg","/img/34-4.jpg","/img/34-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","사우나","라운지","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","드라이기","TV","냉장고"],
                otherService: ["무료주차","카드결제","스프링클러"],
                score: 3.5,
                scoreCount: 5832
            },

            {
                id: 35,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-05-09",
                endDate: "2026-05-13",
                hotelName: "여수 퍼스트라인 오션뷰 콘도",
                price: 159000,
                img: ["/img/35-1.jpg","/img/35-2.jpg","/img/35-3.jpg","/img/35-4.jpg","/img/35-5.jpg"],
                type: "Condo",
                quality: 4,
                publicService: ["피트니스","레스토랑","라운지","엘리베이터","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","전기주전자","냉장고"],
                otherService: ["짐보관가능","카드결제","조식제공"],
                score: 4.0,
                scoreCount: 11230
            },

            {
                id: 36,
                country: "Korea",
                city: "Yeosu",
                startDate: "2026-05-27",
                endDate: "2026-05-31",
                hotelName: "여수 포레스트캠프 글램존",
                price: 92000,
                img: ["/img/36-1.jpg","/img/36-2.jpg","/img/36-3.jpg","/img/36-4.jpg","/img/36-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","레스토랑","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 3987
            },

            /* 한국 - 대전 */

            {
                id: 37,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-03-05",
                endDate: "2026-03-09",
                hotelName: "대전 센트럴파크 시티호텔",
                price: 138000,
                img: ["/img/37-1.jpg","/img/37-2.jpg","/img/37-3.jpg","/img/37-4.jpg","/img/37-5.jpg"],
                type: "Hotel",
                quality: 4,
                publicService: ["레스토랑","라운지","피트니스","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","전기주전자","TV","냉장고","샤워실"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 9210
            },

            {
                id: 38,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-03-18",
                endDate: "2026-03-22",
                hotelName: "대전 포레스트힐 프리미어 리조트",
                price: 167000,
                img: ["/img/38-1.jpg","/img/38-2.jpg","/img/38-3.jpg","/img/38-4.jpg","/img/38-5.jpg"],
                type: "Resort",
                quality: 5,
                publicService: ["야외수영장","실내수영장","레스토랑","라운지","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","욕조","샤워실","TV","드라이기"],
                otherService: ["무료주차","카드결제","조식제공"],
                score: 4.5,
                scoreCount: 14222
            },

            {
                id: 39,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-04-03",
                endDate: "2026-04-07",
                hotelName: "대전 라운지스테이 게스트하우스",
                price: 76000,
                img: ["/img/39-1.jpg","/img/39-2.jpg","/img/39-3.jpg","/img/39-4.jpg","/img/39-5.jpg"],
                type: "GuestHouse",
                quality: 2,
                publicService: ["라운지","편의점","레스토랑","건조기","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","냉장고"],
                otherService: ["스프링클러","카드결제","짐보관가능"],
                score: 3.0,
                scoreCount: 3521
            },

            {
                id: 40,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-04-21",
                endDate: "2026-04-25",
                hotelName: "대전 브리즈라인 시그니처 호텔",
                price: 119000,
                img: ["/img/40-1.jpg","/img/40-2.jpg","/img/40-3.jpg","/img/40-4.jpg","/img/40-5.jpg"],
                type: "Hotel",
                quality: 3,
                publicService: ["레스토랑","사우나","라운지","편의점","엘리베이터","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","TV","드라이기","샤워실","전기주전자"],
                otherService: ["무료주차","카드결제","스프링클러"],
                score: 3.5,
                scoreCount: 5744
            },

            {
                id: 41,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-05-10",
                endDate: "2026-05-14",
                hotelName: "대전 스카이브릿지 오션뷰 콘도",
                price: 155000,
                img: ["/img/41-1.jpg","/img/41-2.jpg","/img/41-3.jpg","/img/41-4.jpg","/img/41-5.jpg"],
                type: "Condo",
                quality: 4,
                publicService: ["피트니스","레스토랑","라운지","엘리베이터","사우나","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","TV","샤워실","냉장고","전기주전자"],
                otherService: ["카드결제","조식제공","짐보관가능"],
                score: 4.0,
                scoreCount: 11190
            },

            {
                id: 42,
                country: "Korea",
                city: "Daejeon",
                startDate: "2026-05-28",
                endDate: "2026-06-01",
                hotelName: "대전 포레스트캠프 스톤글램",
                price: 91000,
                img: ["/img/42-1.jpg","/img/42-2.jpg","/img/42-3.jpg","/img/42-4.jpg","/img/42-5.jpg"],
                type: "Camping",
                quality: 2,
                publicService: ["바베큐","편의점","라운지","탈수기","레스토랑","바"],
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","TV","개인콘센트"],
                otherService: ["캠프파이어","카드결제","스프링클러"],
                score: 3.0,
                scoreCount: 3650
            },

            /* 한국 -광주  */
            {
                id: 43,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-03-07",
                endDate: "2026-03-11",
                hotelName: "그랜드 스카이힐 호텔",
                price: 158000,
                img: ["43-1.jpg","43-2.jpg","43-3.jpg","43-4.jpg","43-5.jpg"],
                type: "호텔",
                quality: 4,
                roomservice: ["무선인터넷","욕실용품","에어컨","드라이기","샤워실","냉장고","TV","금연"],
                publicService: ["피트니스","레스토랑","편의점","라운지","엘리베이터","비즈니스센터"],
                otherService: ["카드결제","무료주차","조식제공"],
                score: 4.0,
                scoreCount: 2471
            },
            {
                id: 44,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-03-19",
                endDate: "2026-03-23",
                hotelName: "라이트하버 리조트",
                price: 121000,
                img: ["44-1.jpg","44-2.jpg","44-3.jpg","44-4.jpg","44-5.jpg"],
                type: "리조트",
                quality: 3,
                roomservice: ["무선인터넷","에어컨","드라이기","샤워실","TV","전기주전자","금연"],
                publicService: ["레스토랑","사우나","편의점","바","라운지","엘리베이터"],
                otherService: ["스프링클러","카드결제","짐보관가능"],
                score: 3.5,
                scoreCount: 5832
            },
            {
                id: 45,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-04-02",
                endDate: "2026-04-06",
                hotelName: "브리즈 라운드 호텔",
                price: 98000,
                img: ["45-1.jpg","45-2.jpg","45-3.jpg","45-4.jpg","45-5.jpg"],
                type: "게스트하우스/비앤비",
                quality: 2,
                roomservice: ["무선인터넷","샤워실","욕실용품","냉장고","TV","개인콘센트","금연"],
                publicService: ["편의점","바","엘리베이터","비즈니스센터","건조기","바베큐"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 3.0,
                scoreCount: 1140
            },
            {
                id: 46,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-04-17",
                endDate: "2026-04-21",
                hotelName: "힐브리즈 콘도",
                price: 142000,
                img: ["46-1.jpg","46-2.jpg","46-3.jpg","46-4.jpg","46-5.jpg"],
                type: "콘도",
                quality: 4,
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","냉장고","TV","객실내취사","전기주전자"],
                publicService: ["레스토랑","사우나","편의점","라운지","엘리베이터","건조기"],
                otherService: ["스프링클러","카드결제","무료주차"],
                score: 4.5,
                scoreCount: 8344
            },
            {
                id: 47,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-05-03",
                endDate: "2026-05-07",
                hotelName: "블루파크 호텔",
                price: 173000,
                img: ["47-1.jpg","47-2.jpg","47-3.jpg","47-4.jpg","47-5.jpg"],
                type: "호텔",
                quality: 5,
                roomservice: ["무선인터넷","욕실용품","욕조","에어컨","TV","냉장고","개인콘센트"],
                publicService: ["피트니스","레스토랑","실내수영장","라운지","엘리베이터","바"],
                otherService: ["카드결제","조식제공","짐보관가능"],
                score: 4.5,
                scoreCount: 9040
            },
            {
                id: 48,
                country: "Korea",
                city: "Gwangju",
                startDate: "2026-05-22",
                endDate: "2026-05-26",
                hotelName: "헤리티지 스테이 호텔",
                price: 76000,
                img: ["48-1.jpg","48-2.jpg","48-3.jpg","48-4.jpg","48-5.jpg"],
                type: "게스트하우스/비앤비",
                quality: 2,
                roomservice: ["무선인터넷","샤워실","에어컨","TV","냉장고","금연"],
                publicService: ["편의점","라운지","엘리베이터","건조기","바베큐","비즈니스센터"],
                otherService: ["카드결제","무료주차","개인사물함"],
                score: 2.5,
                scoreCount: 1988
            },

            /* 한국-제주 */
            {
                id: 49,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-03-03",
                endDate: "2026-03-07",
                hotelName: "오션브리즈 리조텔",
                price: 169000,
                img: ["49-1.jpg","49-2.jpg","49-3.jpg","49-4.jpg","49-5.jpg"],
                type: "리조트",
                quality: 5,
                roomservice: ["무선인터넷","욕조","에어컨","드라이기","냉장고","TV","실내수영장","금연"],
                publicService: ["실내수영장","야외수영장","레스토랑","피트니스","라운지","엘리베이터"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 4.5,
                scoreCount: 12550
            },
            {
                id: 50,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-03-28",
                endDate: "2026-04-01",
                hotelName: "제누스 힐라인 호텔",
                price: 143000,
                img: ["50-1.jpg","50-2.jpg","50-3.jpg","50-4.jpg","50-5.jpg"],
                type: "호텔",
                quality: 4,
                roomservice: ["무선인터넷","욕실용품","에어컨","샤워실","전기주전자","TV","금연"],
                publicService: ["레스토랑","사우나","야외수영장","엘리베이터","라운지","바"],
                otherService: ["카드결제","스프링클러","짐보관가능"],
                score: 4.0,
                scoreCount: 7894
            },
            {
                id: 51,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-04-11",
                endDate: "2026-04-15",
                hotelName: "씨에라 콘도 스위트",
                price: 89000,
                img: ["51-1.jpg","51-2.jpg","51-3.jpg","51-4.jpg","51-5.jpg"],
                type: "콘도",
                quality: 3,
                roomservice: ["무선인터넷","샤워실","객실내취사","냉장고","TV","전기주전자","금연"],
                publicService: ["편의점","엘리베이터","바베큐","건조기","라운지","사우나"],
                otherService: ["무료주차","카드결제","캠프파이어"],
                score: 3.5,
                scoreCount: 3251
            },
            {
                id: 52,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-04-29",
                endDate: "2026-05-03",
                hotelName: "블랑코 서머힐 호텔",
                price: 152000,
                img: ["52-1.jpg","52-2.jpg","52-3.jpg","52-4.jpg","52-5.jpg"],
                type: "호텔",
                quality: 5,
                roomservice: ["무선인터넷","욕조","에어컨","욕실용품","TV","냉장고","개인콘센트"],
                publicService: ["피트니스","레스토랑","실내수영장","엘리베이터","바","라운지"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 4.5,
                scoreCount: 14770
            },
            {
                id: 53,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-05-10",
                endDate: "2026-05-14",
                hotelName: "에메랄드 베이 로지",
                price: 62000,
                img: ["53-1.jpg","53-2.jpg","53-3.jpg","53-4.jpg","53-5.jpg"],
                type: "게스트하우스/비앤비",
                quality: 2,
                roomservice: ["무선인터넷","샤워실","드라이기","TV","냉장고","금연"],
                publicService: ["편의점","라운지","엘리베이터","비즈니스센터","건조기","바베큐"],
                otherService: ["카드결제","개인사물함","조식제공"],
                score: 2.5,
                scoreCount: 1750
            },
            {
                id: 54,
                country: "Korea",
                city: "Jeju",
                startDate: "2026-05-25",
                endDate: "2026-05-29",
                hotelName: "서머필드 캠프 로지",
                price: 54000,
                img: ["54-1.jpg","54-2.jpg","54-3.jpg","54-4.jpg","54-5.jpg"],
                type: "캠핑장",
                quality: 1,
                roomservice: ["무선인터넷","샤워실","개인콘센트","금연","전기주전자","TV"],
                publicService: ["바베큐","편의점","건조기","탈수기","라운지","사우나"],
                otherService: ["캠프파이어","카드결제","무료주차"],
                score: 1.5,
                scoreCount: 1210
            },

            /* 한국-포항 */
            {
                id: 55,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-03-14",
                endDate: "2026-03-18",
                hotelName: "포항 씨라인 호텔",
                price: 112000,
                img: ["55-1.jpg","55-2.jpg","55-3.jpg","55-4.jpg","55-5.jpg"],
                type: "호텔",
                quality: 3,
                roomservice: ["무선인터넷","샤워실","에어컨","TV","냉장고","금연","전기주전자"],
                publicService: ["레스토랑","편의점","엘리베이터","라운지","바","비즈니스센터"],
                otherService: ["카드결제","무료주차","짐보관가능"],
                score: 3.5,
                scoreCount: 3321
            },
            {
                id: 56,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-04-01",
                endDate: "2026-04-05",
                hotelName: "포트웨이브 리조트",
                price: 178000,
                img: ["56-1.jpg","56-2.jpg","56-3.jpg","56-4.jpg","56-5.jpg"],
                type: "리조트",
                quality: 5,
                roomservice: ["무선인터넷","욕조","에어컨","드라이기","냉장고","TV","실내수영장"],
                publicService: ["피트니스","실내수영장","야외수영장","레스토랑","라운지","엘리베이터"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 4.5,
                scoreCount: 14980
            },
            {
                id: 57,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-04-18",
                endDate: "2026-04-22",
                hotelName: "포항 마리나 스테이",
                price: 73000,
                img: ["57-1.jpg","57-2.jpg","57-3.jpg","57-4.jpg","57-5.jpg"],
                type: "게스트하우스/비앤비",
                quality: 2,
                roomservice: ["무선인터넷","샤워실","TV","냉장고","드라이기","금연","전기주전자"],
                publicService: ["편의점","라운지","바베큐","건조기","사우나","엘리베이터"],
                otherService: ["카드결제","개인사물함","무료주차"],
                score: 3.0,
                scoreCount: 2984
            },
            {
                id: 58,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-04-30",
                endDate: "2026-05-04",
                hotelName: "오션스톤 콘도",
                price: 98000,
                img: ["58-1.jpg","58-2.jpg","58-3.jpg","58-4.jpg","58-5.jpg"],
                type: "콘도",
                quality: 3,
                roomservice: ["무선인터넷","샤워실","냉장고","객실내취사","TV","전기주전자","금연"],
                publicService: ["레스토랑","편의점","엘리베이터","야외수영장","바","라운지"],
                otherService: ["카드결제","조식제공","무료주차"],
                score: 3.5,
                scoreCount: 5900
            },
            {
                id: 59,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-05-09",
                endDate: "2026-05-13",
                hotelName: "블루웨이브 캠프",
                price: 55000,
                img: ["59-1.jpg","59-2.jpg","59-3.jpg","59-4.jpg","59-5.jpg"],
                type: "캠핑장",
                quality: 1,
                roomservice: ["무선인터넷","샤워실","전기주전자","TV","금연","개인콘센트"],
                publicService: ["바베큐","편의점","탈수기","건조기","라운지","사우나"],
                otherService: ["캠프파이어","무료주차","카드결제"],
                score: 1.5,
                scoreCount: 1601
            },
            {
                id: 60,
                country: "Korea",
                city: "Pohang",
                startDate: "2026-05-27",
                endDate: "2026-05-31",
                hotelName: "포항 클리프오션 호텔",
                price: 165000,
                img: ["60-1.jpg","60-2.jpg","60-3.jpg","60-4.jpg","60-5.jpg"],
                type: "호텔",
                quality: 4,
                roomservice: ["무선인터넷","욕실용품","에어컨","냉장고","TV","욕조","금연"],
                publicService: ["피트니스","레스토랑","실내수영장","라운지","엘리베이터","바"],
                otherService: ["조식제공","카드결제","무료주차"],
                score: 4.0,
                scoreCount: 8744
            }
    ]

    return(
        <ResortData.Provider value={{hotelData}}>
            {children}
        </ResortData.Provider>
    );
}